In [1]:
import numpy as np
import pandas as pd

In [2]:
# Skipped bad lines using the error_bad_lines argument in read_csv(). This csv is encoded using the latin-1 encoder, the delimiter is ;
pd_BookRatings = pd.read_csv('BX-CSV-Dump/BX-Book-Ratings.csv', delimiter=';', error_bad_lines=False, encoding='latin-1')

pd_Books = pd.read_csv('BX-CSV-Dump/BX-Books.csv', delimiter=';', encoding='latin-1', error_bad_lines=False)

pd_Users = pd.read_csv('BX-CSV-Dump/BX-Users.csv', delimiter=';', encoding='latin-1', error_bad_lines=False)

# join the data frames using the isbn and the user id
pd_combined1 = pd.merge(pd_BookRatings, pd_Books, on='ISBN', how='left')
pd_combined2 =pd.merge(pd_combined1, pd_Users, on='User-ID', how='left')

b'Skipping line 6452: expected 8 fields, saw 9\nSkipping line 43667: expected 8 fields, saw 10\nSkipping line 51751: expected 8 fields, saw 9\n'
b'Skipping line 92038: expected 8 fields, saw 9\nSkipping line 104319: expected 8 fields, saw 9\nSkipping line 121768: expected 8 fields, saw 9\n'
b'Skipping line 144058: expected 8 fields, saw 9\nSkipping line 150789: expected 8 fields, saw 9\nSkipping line 157128: expected 8 fields, saw 9\nSkipping line 180189: expected 8 fields, saw 9\nSkipping line 185738: expected 8 fields, saw 9\n'
b'Skipping line 209388: expected 8 fields, saw 9\nSkipping line 220626: expected 8 fields, saw 9\nSkipping line 227933: expected 8 fields, saw 11\nSkipping line 228957: expected 8 fields, saw 10\nSkipping line 245933: expected 8 fields, saw 9\nSkipping line 251296: expected 8 fields, saw 9\nSkipping line 259941: expected 8 fields, saw 9\nSkipping line 261529: expected 8 fields, saw 9\n'
/home/sammy/data_science/lib/python3.4/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
pd_combined2.head()

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L,Location,Age
0,276725,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,"tyler, texas, usa",NaN
1,276726,0155061224,5,Rites of Passage,Judith Rae,2001,Heinle,http://images.amazon.com/images/P/0155061224.0...,http://images.amazon.com/images/P/0155061224.0...,http://images.amazon.com/images/P/0155061224.0...,"seattle, washington, usa",NaN
2,276727,0446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,"h, new south wales, australia",16.0
3,276729,052165615X,3,Help!: Level 1,Philip Prowse,1999,Cambridge University Press,http://images.amazon.com/images/P/052165615X.0...,http://images.amazon.com/images/P/052165615X.0...,http://images.amazon.com/images/P/052165615X.0...,"rijeka, n/a, croatia",16.0
4,276729,0521795028,6,The Amsterdam Connection : Level 4 (Cambridge ...,Sue Leather,2001,Cambridge University Press,http://images.amazon.com/images/P/0521795028.0...,http://images.amazon.com/images/P/0521795028.0...,http://images.amazon.com/images/P/0521795028.0...,"rijeka, n/a, croatia",16.0

# Recommendation based on rating count. Recommend books based on the number of ratings

In [4]:
pd_combined2.rename(columns={'User-ID':'user_id','ISBN':'isbn', 'Book-Rating':'book_rating','Book-Title':'book_title','Book-Author':'book_author', 'Year-Of-Publication':'publication_year','Publisher':'publisher'}, inplace=True)

In [5]:
pd_combined2.rename(columns={'Location':'location', 'Age':'age'}, inplace=True)

In [6]:
pd_combined2.head(2)

,user_id,isbn,book_rating,book_title,book_author,publication_year,publisher,Image-URL-S,Image-URL-M,Image-URL-L,location,age
0,276725,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,"tyler, texas, usa",NaN
1,276726,0155061224,5,Rites of Passage,Judith Rae,2001,Heinle,http://images.amazon.com/images/P/0155061224.0...,http://images.amazon.com/images/P/0155061224.0...,http://images.amazon.com/images/P/0155061224.0...,"seattle, washington, usa",NaN

In [7]:
pd_combined2[['isbn', 'book_title','book_author', 'publisher','publication_year', 'book_rating']].groupby(['isbn','book_title','book_author']).count().sort_values('book_rating', ascending=False).head(5)

,,,publisher,publication_year,book_rating
isbn,book_title,book_author,,,
0971880107,Wild Animus,Rich Shapero,2502,2502,2502
0316666343,The Lovely Bones: A Novel,Alice Sebold,1295,1295,1295
0385504209,The Da Vinci Code,Dan Brown,883,883,883
0060928336,Divine Secrets of the Ya-Ya Sisterhood: A Novel,Rebecca Wells,732,732,732
0312195516,The Red Tent (Bestselling Backlist),Anita Diamant,723,723,723

# Recommendations based on correlations

First find out the average rating and what the number of ratings each book had

Error: Cannot sort by column book_rating in a multi-index you need to explicitly provide all the levels
NB: When sorting by a MultiIndex you need to contain the tuple describing the column inside a list*

In [8]:
pd_combined2[['isbn', 'book_title','book_author', 'book_rating']].groupby('isbn').agg(['mean', 'count']).sort_values([('book_rating', 'count')],ascending=False).head()

           book_rating
                  mean count
isbn
0971880107    1.019584  2502
0316666343    4.468726  1295
0385504209    4.652322   883
0060928336    3.448087   732
0312195516    4.334716   723

Functions used are groupby(), agg(), sort_values() but with a tuble describing the column i want to sort. This is because it is a multiindex sort

Observation: The book with the highest rating count was not highly rated, thus using this system would be inefficient

In [9]:
user_count = pd_combined2['user_id'].value_counts()
book_count = pd_combined2['isbn'].value_counts()
book_count
pd_combined2[pd_combined2['isbn'].isin(book_count>1000)]
user_count[user_count>=10000]
#pd_combined2['user_id'].isin(user_count[user_count>=10000])
#pd_combined2[pd_combined2['user_id'].isin(user_count[user_count>10000].index)]

11676    13602
Name: user_id, dtype: int64

In [10]:
pd_combined2[['user_id', 'isbn','book_rating']].stack().count()

3449340

In [11]:
pd_combined2[['user_id', 'book_rating']].groupby('user_id').count().sort_values('book_rating', ascending=False).head()

         book_rating
user_id
11676          13602
198711          7550
153662          6109
98391           5891
35859           5850

# value_counts() vs count()

In [12]:
# count() normally used in conjunction with groupby and returns a dataframe
pd_combined2.groupby('user_id').count()
# value_count() normally used by the specific column and returns a series with the column value as the index
pd_combined2['user_id'].value_counts().head()

11676     13602
198711     7550
153662     6109
98391      5891
35859      5850
Name: user_id, dtype: int64

# isin()

In [13]:
# This script returns a series of user_ids with their count
user_count = pd_combined2['user_id'].value_counts()
user_count.head()

11676     13602
198711     7550
153662     6109
98391      5891
35859      5850
Name: user_id, dtype: int64

In [14]:
# As observed above, User id 11676 has a frequency of 13602 in the pd_combined2 dataframe NB: the user_ids is the index

In [15]:
user_count.index

Int64Index([ 11676, 198711, 153662,  98391,  35859, 212898, 278418,  76352,
            110973, 235105,
            ...
              3593,  32263,  30214,  24067,  22018, 158698,  17920, 277135,
            275086, 187812],
           dtype='int64', length=105283)

In [16]:
# Checj the occurences of id 11676
pd_combined2[pd_combined2['user_id']==11676].head()

,user_id,isbn,book_rating,book_title,book_author,publication_year,publisher,Image-URL-S,Image-URL-M,Image-URL-L,location,age
45326,11676,9022906116,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"n/a, n/a, n/a",NaN
45327,11676,"\0432534220\""""",6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"n/a, n/a, n/a",NaN
45328,11676,"\2842053052\""""",7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"n/a, n/a, n/a",NaN
45329,11676,0 7336 1053 6,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"n/a, n/a, n/a",NaN
45330,11676,0=965044153,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"n/a, n/a, n/a",NaN

In [17]:
# This returns a series of the user_ids
pd_combined2['user_id'].head()

0    276725
1    276726
2    276727
3    276729
4    276729
Name: user_id, dtype: int64

In [18]:
# isin() returns boleans , True if item on the left can be found in the right and false if item on the left cannot be found on the right
pd_combined2['user_id'].isin(user_count.index).head()

0    True
1    True
2    True
3    True
4    True
Name: user_id, dtype: bool

In [19]:
# Return the index (user_ids) which have a value count of 6000 or above
user_count[user_count>=6000].index

Int64Index([11676, 198711, 153662], dtype='int64')

In [20]:
# will return booleans with True being where the item on the left has been found in the right
# Can be used as a filter
pd_combined2['user_id'].isin(user_count[user_count>=6000].index).head()

0    False
1    False
2    False
3    False
4    False
Name: user_id, dtype: bool

In [21]:
# Filtering can be done as
pd_combined2[pd_combined2['user_id'].isin(user_count[user_count>=6000].index)==True]
# or 
pd_combined2[pd_combined2['user_id'].isin(user_count[user_count>=6000].index)]
# NB Remember by default during filtering, the items that will be returned in the dataframe will be the items
# that have a True boolean

,user_id,isbn,book_rating,book_title,book_author,publication_year,publisher,Image-URL-S,Image-URL-M,Image-URL-L,location,age
45326,11676,9022906116,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"n/a, n/a, n/a",NaN
45327,11676,"\0432534220\""""",6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"n/a, n/a, n/a",NaN
45328,11676,"\2842053052\""""",7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"n/a, n/a, n/a",NaN
45329,11676,0 7336 1053 6,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"n/a, n/a, n/a",NaN
45330,11676,0=965044153,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"n/a, n/a, n/a",NaN
45331,11676,0000000000,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"n/a, n/a, n/a",NaN
45332,11676,00000000000,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"n/a, n/a, n/a",NaN
45333,11676,0001055666,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"n/a, n/a, n/a",NaN
45334,11676,0001837397,0,Autumn Story Brambly Hedge,Jill Barklem,0,William Collins Sons Co Ltd,http://images.amazon.com/images/P/0001837397.0...,http://images.amazon.com/images/P/0001837397.0...,http://images.amazon.com/images/P/0001837397.0...,"n/a, n/a, n/a",NaN
45335,11676,0001841572,0,Red Shift,Alan Garner,1973,Collins,http://images.amazon.com/images/P/0001841572.0...,http://images.amazon.com/images/P/0001841572.0...,http://images.amazon.com/images/P/0001841572.0...,"n/a, n/a, n/a",NaN
45336,11676,0001848445,0,THE COAL HOUSE T/PB,Andrew Taylor,1986,HarperCollins Publishers,http://images.amazon.com/images/P/0001848445.0...,http://images.amazon.com/images/P/0001848445.0...,http://images.amazon.com/images/P/0001848445.0...,"n/a, n/a, n/a",NaN
45337,11676,0001900277,0,Glue (First Facts - First Skills),Harriet Hains,1989,HarperCollins Publishers,http://images.amazon.com/images/P/0001900277.0...,http://images.amazon.com/images/P/0001900277.0...,http://images.amazon.com/images/P/0001900277.0...,"n/a, n/a, n/a",NaN
45338,11676,0001941941,0,Little Grey Rabbit's Christmas (Collins Colour...,Alison Uttley,1978,HarperCollins Publishers,http://images.amazon.com/images/P/0001941941.0...,http://images.amazon.com/images/P/0001941941.0...,http://images.amazon.com/images/P/0001941941.0...,"n/a, n/a, n/a",NaN
45339,11676,0001944711,6,Count Duckula: Vampire Vacation,Maureen Spurgeon,1988,HarperCollins Publishers,http://images.amazon.com/images/P/0001944711.0...,http://images.amazon.com/images/P/0001944711.0...,http://images.amazon.com/images/P/0001944711.0...,"n/a, n/a, n/a",NaN
45340,11676,0002005018,8,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,"n/a, n/a, n/a",NaN
45341,11676,0002118580,9,Audacity to believe,Sheila Cassidy,1977,Collins,http://images.amazon.com/images/P/0002118580.0...,http://images.amazon.com/images/P/0002118580.0...,http://images.amazon.com/images/P/0002118580.0...,"n/a, n/a, n/a",NaN
45342,11676,0002176432,5,The Financial post selects the 100 best compan...,Eva Innes,1986,Collins,http://images.amazon.com/images/P/0002176432.0...,http://images.amazon.com/images/P/0002176432.0...,http://images.amazon.com/images/P/0002176432.0...,"n/a, n/a, n/a",NaN
45343,11676,0002184974,7,Nigel Mansell My Autobiography,Nigel Mansell,1996,Harpercollins,http://images.amazon.com/images/P/0002184974.0...,http://images.amazon.com/images/P/0002184974.0...,http://images.amazon.com/images/P/0002184974.0...,"n/a, n/a, n/a",NaN
45344,11676,0002220296,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"n/a, n/a, n/a",NaN
45345,11676,000222318,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"n/a, n/a, n/a",NaN
45346,11676,0002245663,0,Forms of Devotion: Stories and Pictures,Diane Schoemperlen,1998,Harpercollins Canada,http://images.amazon.com/images/P/0002245663.0...,http://images.amazon.com/images/P/0002245663.0...,http://images.amazon.com/images/P/0002245663.0...,"n/a, n/a, n/a",NaN
45347,11676,0002246988,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"n/a, n/a, n/a",NaN
45348,11676,0002247283,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"n/a, n/a, n/a",NaN
45349,11676,0002250810,7,Santa Speaks: The Wit and Wisdom of Santas Acr...,Michael Patrick Collins,1995,Harpercollins,http://images.amazon.com/images/P/0002250810.0...,http://images.amazon.com/images/P/0002250810.0...,http://images.amazon.com/images/P/0002250810.0...,"n/a, n/a, n/a",NaN
45350,11676,0002251485,8,Love Isn't Easy (Passionate Peanuts),Charles M. Schulz,1996,Perennial Currents,http://images.amazon.com/images/P/0002251485.0...,http://images.amazon.com/images/P/0002251485.0...,http://images.amazon.com/images/P/0002251485.0...,"n/a, n/a, n/a",NaN
45351,11676,0002255014,8,"Leaning, leaning over water: A novel in ten st...",Frances Itani,1998,HarperCollins,http://images.amazon.com/images/P/0002255014.0...,http://images.amazon.com/images/P/0002255014.0...,http://images.amazon.com/images/P/0002255014.0...,"n/a, n/a, n/a",NaN
45352,11676,0002258560,8,Is Shane MacGowan Still Alive?,Tim Bradford,2000,Flamingo,http://images.amazon.com/images/P/0002258560.0...,http://images.amazon.com/images/P/0002258560.0...,http://images.amazon.com/images/P/0002258560.0...,"n/a, n/a, n/a",NaN
45353,11676,000225929X,10,MARBLE HEART,Gretta Mulrooney,2000,Flamingo,http://images.amazon.com/images/P/000225929X.0...,http://images.amazon.com/images/P/000225929X.0...,http://images.amazon.com/images/P/000225929X.0...,"n/a, n/a, n/a",NaN
45354,11676,0002261456,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"n/a, n/a, n/a",NaN
45355,11676,0002558122,8,Angelas Ashes,Frank Mccourt,0,Harpercollins Australia,http://images.amazon.com/images/P/0002558122.0...,http://images.amazon.com/images/P/0002558122.0...,http://images.amazon.com/images/P/0002558122.0...,"n/a, n/a, n/a",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
823591,198711,1896384013,0,The Golden Key To Heaven,St. Anthony Mary Claret,1955,Immaculate Heart Publications,http://images.amazon.com/images/P/1896384013.0...,http://images.amazon.com/images/P/1896384013.0...,http://images.amazon.com/images/P/1896384013.0...,"little canada, minnesota, usa",62.0
823592,198711,1896938019,0,The Big Race (The Little Dinosaurs' Adventures),Sheryl Paterson,1996,Creative Publishing,http://images.amazon.com/images/P/1896938019.0...,http://images.amazon.com/images/P/1896938019.0...,http://images.amazon.com/images/P/1896938019.0...,"little canada, minnesota, usa",62.0
823593,198711,1896938043,0,1-2-3 Push! (The Little Dinosaurs' Adventures),Sheryl Paterson,1996,Creative Publishing,http://images.amazon.com/images/P/1896938043.0...,http://images.amazon.com/images/P/1896938043.0...,http://images.amazon.com/images/P/1896938043.0...,"little canada, minnesota, usa",62.0
823594,198711,1930623135,0,Shaquille O'Neal (Sports Illustrated For Kids ...,Pohla Smith,2000,"Sports Illustrated For Kids, Time Inc.",http://images.amazon.com/images/P/1930623135.0...,http://images.amazon.com/images/P/1930623135.0...,http://images.amazon.com/images/P/1930623135.0...,"little canada, minnesota, usa",62.0
823595,198711,1930623208,0,Tony Hawk: Chairman of the Board,Sean Mortimer,2000,Sports Illustrated for Kids,http://images.amazon.com/images/P/1930623208.0...,http://images.amazon.com/images/P/1930623208.0...,http://images.amazon.com/images/P/1930623208.0...,"little canada, minnesota, usa",62.0
823596,198711,1932209425,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"little canada, minnesota, usa",62.0
823597,198711,2266001353,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"little canada, minnesota, usa",62.0
823598,198711,2391387604,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"little canada, minnesota, usa",62.0
823599,198711,2764105169,0,Goldilocks and the Three Bears Read-Along Kit,Eric Plouffe,1998,Tormont,http://images.amazon.com/images/P/2764105169.0...,http://images.amazon.com/images/P/2764105169.0...,http://images.amazon.com/images/P/2764105169.0...,"little canada, minnesota, usa",62.0
823600,198711,2894333196,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"little canada, minnesota, usa",62.0
823601,198711,2894333420,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"little canada, minnesota, usa",62.0
823602,198711,2894501129,0,Caillou Plans a Surprise (Backpack (Caillou)),Joceline Sanschagrin,2001,Chouette Editions,http://images.amazon.com/images/P/2894501129.0...,http://images.amazon.com/images/P/2894501129.0...,http://images.amazon.com/images/P/2894501129.0...,"little canada, minnesota, usa",62.0
823603,198711,3473301159,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"little canada, minnesota, usa",62.0
823604,198711,3611619363,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"little canada, minnesota, usa",62.0
823605,198711,394854039,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"little canada, minnesota, usa",62.0
823606,198711,42502310125,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"little canada, minnesota, usa",62.0
823607,198711,44500607095,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"little canada, minnesota, usa",62.0
823608,198711,4891661061,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"little canada, minnesota, usa",62.0
823609,198711,586408008X,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"little canada, minnesota, usa",62.0
823610,198711,6671328798,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"little canada, minnesota, usa",62.0
823611,198711,6941571098,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"little canada, minnesota, usa",62.0
823612,198711,8408021524,0,Braveheart,Randall Wallace,1998,"Editorial Planeta, S.A. (Barcelona)",http://images.amazon.com/images/P/8408021524.0...,http://images.amazon.com/images/P/8408021524.0...,http://images.amazon.com/images/P/8408021524.0...,"little canada, minnesota, usa",62.0
823613,198711,8423900371,0,El Capitban Veneno: El Sombrero de Tres Picos ...,Pedro Antonio De Alarcon,1980,"Espasa Calpe Mexicana, S.A.",http://images.amazon.com/images/P/8423900371.0...,http://images.amazon.com/images/P/8423900371.0...,http://images.amazon.com/images/P/8423900371.0...,"little canada, minnesota, usa",62.0
823614,198711,8427950020,0,Gracias a Winn-Dixie,Kate Dicamillo,2003,Noguer y Caralt Editores,http://images.amazon.com/images/P/8427950020.0...,http://images.amazon.com/images/P/8427950020.0...,http://images.amazon.com/images/P/8427950020.0...,"little canada, minnesota, usa",62.0
823615,198711,8467003995,0,"El Mundo De Ramona (Espasa Juvenil, 192)",Beverly Cleary,2003,Planeta Pub Corp,http://images.amazon.com/images/P/8467003995.0...,http://images.amazon.com/images/P/8467003995.0...,http://images.amazon.com/images/P/8467003995.0...,"little canada, minnesota, usa",62.0
823616,198711,8511839102,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"little canada, minnesota, usa",62.0
823617,198711,9307166813,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"little canada, minnesota, usa",62.0
823618,198711,9590624067,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"little canada, minnesota, usa",62.0
823619,198711,9631172937,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"little canada, minnesota, usa",62.0
823620,198711,9641930266,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"little canada, minnesota, usa",62.0

To ensure statistical significance, users with less than 200 ratings, and books with less than 100 ratings are excluded.

In [22]:
book_count = pd_combined2['isbn'].value_counts()

In [23]:
pd_combined3 = pd_combined2[(pd_combined2['user_id'].isin(user_count[user_count>=200].index) & pd_combined2['isbn'].isin(book_count[book_count>=100].index))]
pd_combined3

,user_id,isbn,book_rating,book_title,book_author,publication_year,publisher,Image-URL-S,Image-URL-M,Image-URL-L,location,age
1456,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...,http://images.amazon.com/images/P/002542730X.0...,http://images.amazon.com/images/P/002542730X.0...,"gilbert, arizona, usa",48.0
1469,277427,0060930535,0,The Poisonwood Bible: A Novel,Barbara Kingsolver,1999,Perennial,http://images.amazon.com/images/P/0060930535.0...,http://images.amazon.com/images/P/0060930535.0...,http://images.amazon.com/images/P/0060930535.0...,"gilbert, arizona, usa",48.0
1471,277427,0060934417,0,Bel Canto: A Novel,Ann Patchett,2002,Perennial,http://images.amazon.com/images/P/0060934417.0...,http://images.amazon.com/images/P/0060934417.0...,http://images.amazon.com/images/P/0060934417.0...,"gilbert, arizona, usa",48.0
1474,277427,0061009059,9,One for the Money (Stephanie Plum Novels (Pape...,Janet Evanovich,1995,HarperTorch,http://images.amazon.com/images/P/0061009059.0...,http://images.amazon.com/images/P/0061009059.0...,http://images.amazon.com/images/P/0061009059.0...,"gilbert, arizona, usa",48.0
1484,277427,0140067477,0,The Tao of Pooh,Benjamin Hoff,1983,Penguin Books,http://images.amazon.com/images/P/0140067477.0...,http://images.amazon.com/images/P/0140067477.0...,http://images.amazon.com/images/P/0140067477.0...,"gilbert, arizona, usa",48.0
1489,277427,014029628X,0,Girl in Hyacinth Blue,Susan Vreeland,2000,Penguin Books,http://images.amazon.com/images/P/014029628X.0...,http://images.amazon.com/images/P/014029628X.0...,http://images.amazon.com/images/P/014029628X.0...,"gilbert, arizona, usa",48.0
1493,277427,014100018X,0,Chocolat,Joanne Harris,2000,Penguin Books,http://images.amazon.com/images/P/014100018X.0...,http://images.amazon.com/images/P/014100018X.0...,http://images.amazon.com/images/P/014100018X.0...,"gilbert, arizona, usa",48.0
1495,277427,0142001740,0,The Secret Life of Bees,Sue Monk Kidd,2003,Penguin Books,http://images.amazon.com/images/P/0142001740.0...,http://images.amazon.com/images/P/0142001740.0...,http://images.amazon.com/images/P/0142001740.0...,"gilbert, arizona, usa",48.0
1513,277427,0312966091,0,Three To Get Deadly : A Stephanie Plum Novel (...,Janet Evanovich,1998,St. Martin's Paperbacks,http://images.amazon.com/images/P/0312966091.0...,http://images.amazon.com/images/P/0312966091.0...,http://images.amazon.com/images/P/0312966091.0...,"gilbert, arizona, usa",48.0
1514,277427,031298328X,0,Full Tilt (Janet Evanovich's Full Series),Janet Evanovich,2003,St. Martin's Paperbacks,http://images.amazon.com/images/P/031298328X.0...,http://images.amazon.com/images/P/031298328X.0...,http://images.amazon.com/images/P/031298328X.0...,"gilbert, arizona, usa",48.0
1516,277427,0316096199,0,Lucky : A Memoir,Alice Sebold,2002,Back Bay Books,http://images.amazon.com/images/P/0316096199.0...,http://images.amazon.com/images/P/0316096199.0...,http://images.amazon.com/images/P/0316096199.0...,"gilbert, arizona, usa",48.0
1517,277427,0316168688,0,The Dogs of Babel (Today Show Book Club #12),Carolyn Parkhurst,2003,"Little, Brown",http://images.amazon.com/images/P/0316168688.0...,http://images.amazon.com/images/P/0316168688.0...,http://images.amazon.com/images/P/0316168688.0...,"gilbert, arizona, usa",48.0
1518,277427,0316284955,0,White Oleander : A Novel (Oprah's Book Club),Janet Fitch,2000,Back Bay Books,http://images.amazon.com/images/P/0316284955.0...,http://images.amazon.com/images/P/0316284955.0...,http://images.amazon.com/images/P/0316284955.0...,"gilbert, arizona, usa",48.0
1519,277427,0316569321,0,White Oleander : A Novel,Janet Fitch,1999,"Little, Brown",http://images.amazon.com/images/P/0316569321.0...,http://images.amazon.com/images/P/0316569321.0...,http://images.amazon.com/images/P/0316569321.0...,"gilbert, arizona, usa",48.0
1520,277427,0316602051,0,The Jester,James Patterson,2003,"Little, Brown",http://images.amazon.com/images/P/0316602051.0...,http://images.amazon.com/images/P/0316602051.0...,http://images.amazon.com/images/P/0316602051.0...,"gilbert, arizona, usa",48.0
1521,277427,0316666343,0,The Lovely Bones: A Novel,Alice Sebold,2002,"Little, Brown",http://images.amazon.com/images/P/0316666343.0...,http://images.amazon.com/images/P/0316666343.0...,http://images.amazon.com/images/P/0316666343.0...,"gilbert, arizona, usa",48.0
1522,277427,0316776963,8,Me Talk Pretty One Day,David Sedaris,2001,Back Bay Books,http://images.amazon.com/images/P/0316776963.0...,http://images.amazon.com/images/P/0316776963.0...,http://images.amazon.com/images/P/0316776963.0...,"gilbert, arizona, usa",48.0
1523,277427,0316777730,0,Naked,David Sedaris,1998,Back Bay Books,http://images.amazon.com/images/P/0316777730.0...,http://images.amazon.com/images/P/0316777730.0...,http://images.amazon.com/images/P/0316777730.0...,"gilbert, arizona, usa",48.0
1533,277427,0345339681,0,The Hobbit : The Enchanting Prelude to The Lor...,J.R.R. TOLKIEN,1986,Del Rey,http://images.amazon.com/images/P/0345339681.0...,http://images.amazon.com/images/P/0345339681.0...,http://images.amazon.com/images/P/0345339681.0...,"gilbert, arizona, usa",48.0
1535,277427,0345361792,0,A Prayer for Owen Meany,John Irving,1990,Ballantine Books,http://images.amazon.com/images/P/0345361792.0...,http://images.amazon.com/images/P/0345361792.0...,http://images.amazon.com/images/P/0345361792.0...,"gilbert, arizona, usa",48.0
1543,277427,0345413903,10,The Murder Book,Jonathan Kellerman,2003,Ballantine Books,http://images.amazon.com/images/P/0345413903.0...,http://images.amazon.com/images/P/0345413903.0...,http://images.amazon.com/images/P/0345413903.0...,"gilbert, arizona, usa",48.0
1545,277427,0345436911,0,The Dress Lodger (Ballantine Reader's Circle),Sheri Holman,2001,Ballantine Books,http://images.amazon.com/images/P/0345436911.0...,http://images.amazon.com/images/P/0345436911.0...,http://images.amazon.com/images/P/0345436911.0...,"gilbert, arizona, usa",48.0
1553,277427,0374199698,0,Middlesex: A Novel,Jeffrey Eugenides,2002,"Farrar, Straus and Giroux",http://images.amazon.com/images/P/0374199698.0...,http://images.amazon.com/images/P/0374199698.0...,http://images.amazon.com/images/P/0374199698.0...,"gilbert, arizona, usa",48.0
1559,277427,0375727132,0,The Dive From Clausen's Pier : A Novel (Vintag...,ANN PACKER,2003,Vintage,http://images.amazon.com/images/P/0375727132.0...,http://images.amazon.com/images/P/0375727132.0...,http://images.amazon.com/images/P/0375727132.0...,"gilbert, arizona, usa",48.0
1566,277427,0380710218,0,Postmortem,Patricia Daniels Cornwell,1993,Harper Mass Market Paperbacks (Mm),http://images.amazon.com/images/P/0380710218.0...,http://images.amazon.com/images/P/0380710218.0...,http://images.amazon.com/images/P/0380710218.0...,"gilbert, arizona, usa",48.0
1568,277427,0380718332,0,All That Remains (Kay Scarpetta Mysteries (Pap...,Patricia D. Cornwell,1993,Avon,http://images.amazon.com/images/P/0380718332.0...,http://images.amazon.com/images/P/0380718332.0...,http://images.amazon.com/images/P/0380718332.0...,"gilbert, arizona, usa",48.0
1578,277427,0385424736,9,The Rainmaker,John Grisham,1995,Doubleday Books,http://images.amazon.com/images/P/0385424736.0...,http://images.amazon.com/images/P/0385424736.0...,http://images.amazon.com/images/P/0385424736.0...,"gilbert, arizona, usa",48.0
1580,277427,0385484518,0,"Tuesdays with Morrie: An Old Man, a Young Man,...",MITCH ALBOM,1997,Doubleday,http://images.amazon.com/images/P/0385484518.0...,http://images.amazon.com/images/P/0385484518.0...,http://images.amazon.com/images/P/0385484518.0...,"gilbert, arizona, usa",48.0
1581,277427,0385486804,9,Into the Wild,Jon Krakauer,1997,Anchor,http://images.amazon.com/images/P/0385486804.0...,http://images.amazon.com/images/P/0385486804.0...,http://images.amazon.com/images/P/0385486804.0...,"gilbert, arizona, usa",48.0
1584,277427,0385504209,8,The Da Vinci Code,Dan Brown,2003,Doubleday,http://images.amazon.com/images/P/0385504209.0...,http://images.amazon.com/images/P/0385504209.0...,http://images.amazon.com/images/P/0385504209.0...,"gilbert, arizona, usa",48.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1146882,275970,0451203771,0,Scarlet Feather,Maeve Binchy,2002,Signet Book,http://images.amazon.com/images/P/0451203771.0...,http://images.amazon.com/images/P/0451203771.0...,http://images.amazon.com/images/P/0451203771.0...,"pittsburgh, pennsylvania, usa",46.0
1146883,275970,0451206525,0,Dead Sleep,Greg Iles,2002,Signet Book,http://images.amazon.com/images/P/0451206525.0...,http://images.amazon.com/images/P/0451206525.0...,http://images.amazon.com/images/P/0451206525.0...,"pittsburgh, pennsylvania, usa",46.0
1146893,275970,0451524934,0,1984,George Orwell,1990,Signet Book,http://images.amazon.com/images/P/0451524934.0...,http://images.amazon.com/images/P/0451524934.0...,http://images.amazon.com/images/P/0451524934.0...,"pittsburgh, pennsylvania, usa",46.0
1146894,275970,0451526341,0,Animal Farm,George Orwell,2004,Signet,http://images.amazon.com/images/P/0451526341.0...,http://images.amazon.com/images/P/0451526341.0...,http://images.amazon.com/images/P/0451526341.0...,"pittsburgh, pennsylvania, usa",46.0
1146896,275970,0452260116,0,Song of Solomon (Oprah's Book Club (Paperback)),Toni Morrison,1987,Plume Books,http://images.amazon.com/images/P/0452260116.0...,http://images.amazon.com/images/P/0452260116.0...,http://images.amazon.com/images/P/0452260116.0...,"pittsburgh, pennsylvania, usa",46.0
1146898,275970,0452269571,0,Bastard Out of Carolina,Dorothy Allison,1993,Plume Books,http://images.amazon.com/images/P/0452269571.0...,http://images.amazon.com/images/P/0452269571.0...,http://images.amazon.com/images/P/0452269571.0...,"pittsburgh, pennsylvania, usa",46.0
1146904,275970,0452282195,0,The Bluest Eye,Toni Morrison,2000,Plume Books,http://images.amazon.com/images/P/0452282195.0...,http://images.amazon.com/images/P/0452282195.0...,http://images.amazon.com/images/P/0452282195.0...,"pittsburgh, pennsylvania, usa",46.0
1146910,275970,0452284449,0,The Virgin Blue,Tracy Chevalier,2003,Plume Books,http://images.amazon.com/images/P/0452284449.0...,http://images.amazon.com/images/P/0452284449.0...,http://images.amazon.com/images/P/0452284449.0...,"pittsburgh, pennsylvania, usa",46.0
1146963,275970,0525947647,0,Lies and the Lying Liars Who Tell Them: A Fair...,Al Franken,2003,Dutton Books,http://images.amazon.com/images/P/0525947647.0...,http://images.amazon.com/images/P/0525947647.0...,http://images.amazon.com/images/P/0525947647.0...,"pittsburgh, pennsylvania, usa",46.0
1146984,275970,0553250531,0,The Valley of Horses,JEAN M. AUEL,1984,Bantam,http://images.amazon.com/images/P/0553250531.0...,http://images.amazon.com/images/P/0553250531.0...,http://images.amazon.com/images/P/0553250531.0...,"pittsburgh, pennsylvania, usa",46.0
1146988,275970,0553268880,0,The Prince of Tides,Pat Conroy,1987,Bantam Books,http://images.amazon.com/images/P/0553268880.0...,http://images.amazon.com/images/P/0553268880.0...,http://images.amazon.com/images/P/0553268880.0...,"pittsburgh, pennsylvania, usa",46.0
1146989,275970,0553272535,0,Night,Elie Wiesel,1982,Bantam Books,http://images.amazon.com/images/P/0553272535.0...,http://images.amazon.com/images/P/0553272535.0...,http://images.amazon.com/images/P/0553272535.0...,"pittsburgh, pennsylvania, usa",46.0
1146990,275970,0553275976,0,The Bonfire of the Vanities,Tom Wolfe,1988,Bantam Books,http://images.amazon.com/images/P/0553275976.0...,http://images.amazon.com/images/P/0553275976.0...,http://images.amazon.com/images/P/0553275976.0...,"pittsburgh, pennsylvania, usa",46.0
1146991,275970,0553277472,0,Zen and the Art of Motorcycle Maintenance: An ...,ROBERT PIRSIG,1984,Bantam,http://images.amazon.com/images/P/0553277472.0...,http://images.amazon.com/images/P/0553277472.0...,http://images.amazon.com/images/P/0553277472.0...,"pittsburgh, pennsylvania, usa",46.0
1146993,275970,0553279378,0,I Know Why the Caged Bird Sings,MAYA ANGELOU,1983,Bantam,http://images.amazon.com/images/P/0553279378.0...,http://images.amazon.com/images/P/0553279378.0...,http://images.amazon.com/images/P/0553279378.0...,"pittsburgh, pennsylvania, usa",46.0
1146996,275970,0553375407,0,Ishmael: An Adventure of the Mind and Spirit,Daniel Quinn,1995,Bantam,http://images.amazon.com/images/P/0553375407.0...,http://images.amazon.com/images/P/0553375407.0...,http://images.amazon.com/images/P/0553375407.0...,"pittsburgh, pennsylvania, usa",46.0
1147061,275970,0671027344,0,The Perks of Being a Wallflower,Stephen Chbosky,1999,MTV,http://images.amazon.com/images/P/0671027344.0...,http://images.amazon.com/images/P/0671027344.0...,http://images.amazon.com/images/P/0671027344.0...,"pittsburgh, pennsylvania, usa",46.0
1147106,275970,0679731725,0,The Remains of the Day (Vintage International),Kazuo Ishiguro,1993,Vintage Books USA,http://images.amazon.com/images/P/0679731725.0...,http://images.amazon.com/images/P/0679731725.0...,http://images.amazon.com/images/P/0679731725.0...,"pittsburgh, pennsylvania, usa",46.0
1147110,275970,0679734775,0,The House on Mango Street (Vintage Contemporar...,SANDRA CISNEROS,1991,Vintage,http://images.amazon.com/images/P/0679734775.0...,http://images.amazon.com/images/P/0679734775.0...,http://images.amazon.com/images/P/0679734775.0...,"pittsburgh, pennsylvania, usa",46.0
1147151,275970,0684874350,0,ANGELA'S ASHES,Frank McCourt,1996,Scribner,http://images.amazon.com/images/P/0684874350.0...,http://images.amazon.com/images/P/0684874350.0...,http://images.amazon.com/images/P/0684874350.0...,"pittsburgh, pennsylvania, usa",46.0
1147208,275970,0743412028,0,Pay It Forward,Catherine Ryan Hyde,2000,Pocket,http://images.amazon.com/images/P/0743412028.0...,http://images.amazon.com/images/P/0743412028.0...,http://images.amazon.com/images/P/0743412028.0...,"pittsburgh, pennsylvania, usa",46.0
1147228,275970,0749397543,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"pittsburgh, pennsylvania, usa",46.0
1147251,275970,0767902521,0,A Walk in the Woods: Rediscovering America on ...,Bill Bryson,1999,Broadway Books,http://images.amazon.com/images/P/0767902521.0...,http://images.amazon.com/images/P/0767902521.0...,http://images.amazon.com/images/P/0767902521.0...,"pittsburgh, pennsylvania, usa",46.0
1147271,275970,0786866586,0,Shopgirl : A Novella,Steve Martin,2000,Hyperion Press,http://images.amazon.com/images/P/0786866586.0...,http://images.amazon.com/images/P/0786866586.0...,http://images.amazon.com/images/P/0786866586.0...,"pittsburgh, pennsylvania, usa",46.0
1147294,275970,0802139256,0,Peace Like a River,Leif Enger,2002,Grove Press,http://images.amazon.com/images/P/0802139256.0...,http://images.amazon.com/images/P/0802139256.0...,http://images.amazon.com/images/P/0802139256.0...,"pittsburgh, pennsylvania, usa",46.0
1147304,275970,0804111359,0,Secret History,DONNA TARTT,1993,Ballantine Books,http://images.amazon.com/images/P/0804111359.0...,http://images.amazon.com/images/P/0804111359.0...,http://images.amazon.com/images/P/0804111359.0...,"pittsburgh, pennsylvania, usa",46.0
1147436,275970,140003065X,0,A Fine Balance,Rohinton Mistry,2001,Vintage Books USA,http://images.amazon.com/images/P/140003065X.0...,http://images.amazon.com/images/P/140003065X.0...,http://images.amazon.com/images/P/140003065X.0...,"pittsburgh, pennsylvania, usa",46.0
1147439,275970,1400031346,0,The No. 1 Ladies' Detective Agency,Alexander McCall Smith,2002,Anchor (UK),http://images.amazon.com/images/P/1400031346.0...,http://images.amazon.com/images/P/1400031346.0...,http://images.amazon.com/images/P/1400031346.0...,"pittsburgh, pennsylvania, usa",46.0
1147440,275970,1400031354,0,Tears of the Giraffe (No.1 Ladies Detective Ag...,Alexander McCall Smith,2002,Anchor,http://images.amazon.com/images/P/1400031354.0...,http://images.amazon.com/images/P/1400031354.0...,http://images.amazon.com/images/P/1400031354.0...,"pittsburgh, pennsylvania, usa",46.0
1147441,275970,1400031362,0,Morality for Beautiful Girls (No.1 Ladies Dete...,Alexander McCall Smith,2002,Anchor,http://images.amazon.com/images/P/1400031362.0...,http://images.amazon.com/images/P/1400031362.0...,http://images.amazon.com/images/P/1400031362.0...,"pittsburgh, pennsylvania, usa",46.0

# Find out which book is second most rated

In [24]:
pd_combined2[['isbn', 'book_title', 'book_rating']].groupby(['isbn','book_title']).count().sort_values('book_rating',ascending=False).head()

                                                            book_rating
isbn       book_title
0971880107 Wild Animus                                             2502
0316666343 The Lovely Bones: A Novel                               1295
0385504209 The Da Vinci Code                                        883
0060928336 Divine Secrets of the Ya-Ya Sisterhood: A Novel          732
0312195516 The Red Tent (Bestselling Backlist)                      723

# Find out which books are correlated with the second most rated book The Lovely Bones: A Novel

In [25]:
#pd_combined3[['book_rating']]
pd_combined3[['book_rating']][pd_combined3['isbn']== '0971880107'].corrwith(pd_combined3[['book_rating']][pd_combined3['isbn']== '0316666343'])

book_rating   NaN
dtype: float64

In [26]:
ratings_pivot = pd_combined3.pivot(index='user_id', columns='isbn').book_rating

In [27]:
ratings_pivot['0316666343']
ratings_pivot.corrwith(ratings_pivot['0316666343'])
PearsonR_pd = pd.DataFrame(ratings_pivot.corrwith(ratings_pivot['0316666343']), columns=['pearsonR'])

In [28]:

book_rating_count = pd_combined3[['isbn','book_rating']].groupby('isbn').count().sort_values('book_rating')

In [29]:
PearsonR_pd.join(book_rating_count).sort_values('pearsonR', ascending=False).head()

            pearsonR  book_rating
isbn
0316666343  1.000000          272
0345441036  0.750588           32
0552124753  0.704187           29
0684867621  0.618834           36
0446519138  0.600658           30

# Collaborative Filtering Using k-Nearest Neighbors (kNN)

KNN is a machine learning algorithm to find clusters of similar users based on common book ratings and make predictions using the average rating of top-k nearest neighbors

In [ ]:
# pivot the dataset so that the columns represent the user ids and the rows represent the books isbn and the cell values to represent the book ratings

In [33]:
# First trim the data set to avoid out of memory error
pd_combined2[['isbn', 'user_id', 'book_rating']].groupby('isbn')

In [35]:
#book_ratings_pivot = pd_combined2.pivot(index='isbn', columns='user_id', values='book_rating')
columns_toDrop = ['publication_year', 'publisher', 'book_author', 'Image-URL-S', 'Image-URL-M', 'Image-URL-L']
pd_combined4 = pd_combined2.drop(columns_toDrop, axis=1)
pd_combined4.head()

,user_id,isbn,book_rating,book_title,location,age
0,276725,034545104X,0,Flesh Tones: A Novel,"tyler, texas, usa",NaN
1,276726,0155061224,5,Rites of Passage,"seattle, washington, usa",NaN
2,276727,0446520802,0,The Notebook,"h, new south wales, australia",16.0
3,276729,052165615X,3,Help!: Level 1,"rijeka, n/a, croatia",16.0
4,276729,0521795028,6,The Amsterdam Connection : Level 4 (Cambridge ...,"rijeka, n/a, croatia",16.0

In [39]:
# Goup by ISBN and add a column for total rating count
book_ratingCount = pd_combined4[['isbn', 'book_rating']].groupby('isbn').count().reset_index().rename(columns={'book_rating':'book_rating_count'})
book_ratingCount.head()

          isbn  book_rating_count
0   0330299891                  2
1   0375404120                  2
2   0586045007                  1
3   9022906116                  2
4   9032803328                  1

In [41]:
pd_CombinedRateCount = pd_combined4.merge(book_ratingCount, left_on='isbn', right_on='isbn', how='left')
pd_CombinedRateCount.head()

,user_id,isbn,book_rating,book_title,location,age,book_rating_count
0,276725,034545104X,0,Flesh Tones: A Novel,"tyler, texas, usa",NaN,60
1,276726,0155061224,5,Rites of Passage,"seattle, washington, usa",NaN,2
2,276727,0446520802,0,The Notebook,"h, new south wales, australia",16.0,116
3,276729,052165615X,3,Help!: Level 1,"rijeka, n/a, croatia",16.0,1
4,276729,0521795028,6,The Amsterdam Connection : Level 4 (Cambridge ...,"rijeka, n/a, croatia",16.0,1

In [52]:
pd_CombinedRateCount[['user_id', 'isbn', 'book_title', 'book_rating_count']][pd_CombinedRateCount['isbn']=='034545104X']

         user_id        isbn            book_title  book_rating_count
0         276725  034545104X  Flesh Tones: A Novel                 60
15433       2313  034545104X  Flesh Tones: A Novel                 60
27533       6543  034545104X  Flesh Tones: A Novel                 60
36088       8680  034545104X  Flesh Tones: A Novel                 60
40794      10314  034545104X  Flesh Tones: A Novel                 60
101553     23768  034545104X  Flesh Tones: A Novel                 60
122936     28266  034545104X  Flesh Tones: A Novel                 60
123655     28523  034545104X  Flesh Tones: A Novel                 60
179476     39002  034545104X  Flesh Tones: A Novel                 60
215546     50403  034545104X  Flesh Tones: A Novel                 60
243661     56157  034545104X  Flesh Tones: A Novel                 60
255428     59102  034545104X  Flesh Tones: A Novel                 60
256846     59287  034545104X  Flesh Tones: A Novel                 60
274431     63970  034545104X  Flesh Tones: A Novel                 60
325432     77480  034545104X  Flesh Tones: A Novel                 60
326772     77940  034545104X  Flesh Tones: A Novel                 60
343933     81977  034545104X  Flesh Tones: A Novel                 60
390851     94362  034545104X  Flesh Tones: A Novel                 60
407178     98391  034545104X  Flesh Tones: A Novel                 60
469774    112199  034545104X  Flesh Tones: A Novel                 60
485304    115435  034545104X  Flesh Tones: A Novel                 60
509668    123981  034545104X  Flesh Tones: A Novel                 60
530849    128045  034545104X  Flesh Tones: A Novel                 60
531617    128276  034545104X  Flesh Tones: A Novel                 60
535919    129311  034545104X  Flesh Tones: A Novel                 60
550631    132081  034545104X  Flesh Tones: A Novel                 60
553625    133235  034545104X  Flesh Tones: A Novel                 60
559785    135045  034545104X  Flesh Tones: A Novel                 60
575922    138543  034545104X  Flesh Tones: A Novel                 60
598121    144315  034545104X  Flesh Tones: A Novel                 60
598528    144486  034545104X  Flesh Tones: A Novel                 60
602125    145451  034545104X  Flesh Tones: A Novel                 60
610242    147799  034545104X  Flesh Tones: A Novel                 60
654755    158506  034545104X  Flesh Tones: A Novel                 60
670881    163202  034545104X  Flesh Tones: A Novel                 60
693259    168816  034545104X  Flesh Tones: A Novel                 60
707722    171912  034545104X  Flesh Tones: A Novel                 60
717945    173743  034545104X  Flesh Tones: A Novel                 60
723356    174834  034545104X  Flesh Tones: A Novel                 60
778339    188513  034545104X  Flesh Tones: A Novel                 60
803631    195374  034545104X  Flesh Tones: A Novel                 60
859823    208019  034545104X  Flesh Tones: A Novel                 60
861311    208406  034545104X  Flesh Tones: A Novel                 60
870270    210597  034545104X  Flesh Tones: A Novel                 60
888388    214011  034545104X  Flesh Tones: A Novel                 60
907678    220502  034545104X  Flesh Tones: A Novel                 60
936446    227106  034545104X  Flesh Tones: A Novel                 60
937748    227447  034545104X  Flesh Tones: A Novel                 60
939959    227520  034545104X  Flesh Tones: A Novel                 60
941592    227886  034545104X  Flesh Tones: A Novel                 60
999983    240144  034545104X  Flesh Tones: A Novel                 60
1015263   243142  034545104X  Flesh Tones: A Novel                 60
1019576   244420  034545104X  Flesh Tones: A Novel                 60
1069872   255502  034545104X  Flesh Tones: A Novel                 60
1076917   257492  034545104X  Flesh Tones: A Novel                 60
1088130   260897  034545104X  Flesh Tones: A Novel                 60
1096056   263003  034545104X  Flesh Tones: A Novel                 60
1117909   268191  034545104X  Flesh Tones: A Novel                 60
1131746   271448  034545104X  Flesh Tones: A Novel                 60
1143819   274925  034545104X  Flesh Tones: A Novel                 60